# Generated by Django 4.0.3 on 2022-03-16 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField()),
                ('password_hash', models.CharField(max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='admin_actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='admin_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('abilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('uploaded_date', models.DateTimeField()),
                ('file_url', models.CharField(max_length=250)),
                ('is_used', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_public', models.BooleanField()),
                ('moderators', models.TextField()),
                ('state', models.CharField(max_length=10)),
                ('users_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='message_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='object_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=20)),
                ('object_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('moderators', models.TextField()),
                ('users_num', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.category')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text_content', models.TextField()),
                ('pictures', models.TextField(null=True)),
                ('who_can_see', models.TextField()),
                ('interaction_counter', models.CharField(max_length=50)),
                ('post_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='setting_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=50)),
                ('default_value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=70)),
                ('creation_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField()),
                ('encrypted_key', models.CharField(max_length=50)),
                ('seed', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password_hash', models.CharField(max_length=72)),
                ('phone_number', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=None, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video_urls', models.TextField()),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('modify_date', models.DateTimeField()),
                ('setting_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.setting_code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='user_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reason', models.TextField()),
                ('action_date', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.admin_actions')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(max_length=100)),
                ('link', models.URLField()),
                ('pfp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfp', to='database.file')),
                ('pfpback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfpback', to='database.file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='post_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='post_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.page')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post')),
            ],
        ),
        migrations.CreateModel(
            name='post_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.group')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.video'),
        ),
        migrations.CreateModel(
            name='particpant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField()),
                ('last_read', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user'),
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField()),
                ('time_read', models.DateTimeField()),
                ('is_read', models.BooleanField()),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.activity_type')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.object_type')),
                ('receipt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='database.user')),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('delete_date', models.DateTimeField()),
                ('last_read', models.DateTimeField()),
                ('is_read', models.BooleanField()),
                ('readers', models.CharField(max_length=100, null=True)),
                ('message_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.message_type')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.particpant')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.thread')),
            ],
        ),
        migrations.CreateModel(
            name='group_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user'),
        ),
        migrations.CreateModel(
            name='friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('send_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='database.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='database.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attach_url', models.TextField()),
                ('date', models.DateTimeField()),
                ('interaction_counter', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=None, null=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='database.user')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='database.user')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.admin_level'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
    ]
