# Generated by Django 4.0.3 on 2022-03-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pic_url',
            new_name='pfp',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='backpic_url',
            new_name='pfpback',
        ),
    ]
