# Generated by Django 4.0.3 on 2022-03-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
