# Generated by Django 3.2.8 on 2022-03-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attach_url',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_position',
            field=models.CharField(default='main', max_length=5),
        ),
        migrations.AddField(
            model_name='comment',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='interaction_counter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='post_react',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='like', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_to', to='database.comment')),
                ('replyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyer', to='database.comment')),
            ],
        ),
        migrations.CreateModel(
            name='comment_react',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='like', max_length=10)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
