# Generated by Django 4.0.3 on 2022-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_user_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Lt_t_un_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
