# Generated by Django 4.0.3 on 2022-03-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_pic_url_profile_pfp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
