# Generated by Django 4.0.3 on 2022-03-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user_lt_t_un_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='postfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('uploaded_date', models.DateTimeField()),
                ('file_url', models.CharField(max_length=250)),
                ('is_used', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_state',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='edit_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_location',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='attach_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.file'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.particpant'),
        ),
        migrations.DeleteModel(
            name='video',
        ),
        migrations.AddField(
            model_name='postfile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.post'),
        ),
    ]
