# Generated by Django 4.0.3 on 2022-03-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_file_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
