# Generated by Django 4.0.3 on 2022-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
