# Generated by Django 4.0.3 on 2022-03-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_postfile_rename_date_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.post'),
        ),
    ]
