# Generated by Django 4.0.3 on 2022-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_file_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.CharField(max_length=250),
        ),
    ]
