# Generated by Django 4.0.4 on 2022-04-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_object_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='page',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='encrypted_key',
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user'),
        ),
        migrations.AddField(
            model_name='thread',
            name='type',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverr', to='database.user'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderr', to='database.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users_num',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='particpant',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='particpant',
            name='is_active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='particpant',
            name='last_read',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='delete_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='update_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
