# Generated by Django 4.0.4 on 2022-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_friendship_receiver_alter_friendship_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
