# Generated by Django 4.0.4 on 2022-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_notification_time_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
