# Generated by Django 4.0.4 on 2022-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_notification_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='seed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
