# Generated by Django 4.0.4 on 2022-05-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_thread_delete_date_alter_thread_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particpant',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='particpant',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='particpant',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
