# Generated by Django 4.0.4 on 2022-05-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_particpant_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='readers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.user'),
        ),
        migrations.DeleteModel(
            name='message_type',
        ),
    ]
