# Generated by Django 4.0.4 on 2022-06-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_group_description_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grouppfp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.file'),
        ),
    ]
